### ISSUE TITLE
Remake result of submit forms 

### ISSUE THREAD

**Issue by anastasiiaShtepa** [jmas/a-shtepa-issues#2]
**“Який результат я хочу отримати:“**

![image](https://user-images.githubusercontent.com/113911141/191025921-5c32dde7-4fe1-4811-bc67-5ddf56fd5d5c.png)
Анна, переслала мені редагування. По всім сторінкам. Мені твої можна виправлять чи ти сам?

**“Поточний результат:“**
![image](https://user-images.githubusercontent.com/113911141/191026688-198cd33b-bd89-456f-8cd6-0f17629eda70.png)
**Careers page**
![image](https://user-images.githubusercontent.com/113911141/191026932-d8409a40-4b2b-4069-9029-f3d7ca21ded1.png)
**Users Page**
![image](https://user-images.githubusercontent.com/113911141/191027148-c00232b1-a6ab-473b-91c1-0280e061cf3a.png)

**Comment by jmas** [comment]
Done
