### ISSUE TITLE
Add points for backend

### ISSUE THREAD

**Issue by anastasiiaShtepa** [jmas/a-shtepa-issues#3]
Яким чином робити addpoints для хлопців з backend/   Анна чекає подробиць.

**Comment by jmas** [comment]
endpoint

**Comment by jmas** [comment]
endpoint

**Comment by jmas** [comment]
endpoint

**Comment by jmas** [comment]
Нам потрібен ендпоінт для завантаження CV PDF файлу (до 10 мб) і отримання посилання на цей файл для подальшої передачі цього урла у формі "Карєра".

Як може виглядати і працювати цей ендпоінт:

**Назва:** `https://example.com/cv`

**Метод:** `POST` або `PUT`

**Поля (дані) запроса:**

```
file: (binary)
```

**Валідація:** до 10 мб, тип PDF

**Comment by jmas** [comment]
Нам потрібен ендпоінт для завантаження CV PDF файлу (до 10 мб) і отримання посилання на цей файл для подальшої передачі цього урла у формі "Карєра".

Як може виглядати і працювати цей ендпоінт:

**Назва:** `https://example.com/cv`

**Метод:** `POST` або `PUT`

**Поля (дані) запроса:**

```
file: (binary)
```

**Валідація:** до 10 мб, тип PDF

**Comment by jmas** [comment]
Нам потрібен ендпоінт для завантаження CV PDF файлу (до 10 мб) і отримання посилання на цей файл для подальшої передачі цього урла у формі "Карєра".

Як може виглядати і працювати цей ендпоінт:

**Назва:** `https://example.com/cv`

**Метод:** `POST` або `PUT`

**Поля (дані) запроса:**

```
file: (binary)
```

**Валідація:** до 10 мб, тип PDF
