### ISSUE TITLE
На всіх сторінках зробила поправки по формах

### ISSUE THREAD

**Issue by anastasiiaShtepa** [jmas/a-shtepa-issues#4]
**“Поточний результат“:**
![image](https://user-images.githubusercontent.com/113911141/191036548-01289fd1-0e43-45d8-8914-2c535d930954.png)
Форма Юзери
![image](https://user-images.githubusercontent.com/113911141/191036726-45132f67-1aa8-462e-9c69-ff992c8996eb.png)
Мерчанти
![image](https://user-images.githubusercontent.com/113911141/191036985-51a4cbb5-a4b7-416d-9057-69ceb1dda6f1.png)
Careers

**Comment by jmas** [comment]
Done.
