### ISSUE TITLE
Problems with attached files

### ISSUE THREAD

**Issue by anastasiiaShtepa** [jmas/a-shtepa-issues#5]
Який результат ти хочеш отримати: Питання в тому, якщо юзер захоче додати більше одного пдф файла. Виходить не гарно коли більше одного файла. В макеті такого немає, там тільки до завантаження є один файл. 
![image](https://user-images.githubusercontent.com/113911141/191446447-e45f5411-d855-4d17-968c-541fdcb8e033.png)
![image](https://user-images.githubusercontent.com/113911141/191447915-9ee87bc5-e763-4012-8930-1d6df3285ecf.png)
Поточний результат: 
![image](https://user-images.githubusercontent.com/113911141/191448078-5593e3b0-7b7a-4843-b222-9b6fde11dc2a.png)

Скріншот кода який відповідає за додані файли
![image](https://user-images.githubusercontent.com/113911141/191448740-d2c1602f-1f36-4969-bc3d-3101f27a444d.png)

**Comment by anastasiiaShtepa** [comment]
Є ідея для вирішення цього питання. Була мені надана пропозиція взагалі більше одного файла не підгружати. Потрібна допомога з реалізацією в код. 
if (files.length > 1) {
      removeFile(files[0]);
    }

**Comment by jmas** [comment]
@anastasiiaShtepa Так, погоджуюсь не треба більше одного файла додавати.

**Comment by anastasiiaShtepa** [comment]
Done
