### ISSUE TITLE
Виправлення по коду

### ISSUE THREAD

**Issue by anastasiiaShtepa** [jmas/a-shtepa-issues#7]
Моя мета: 
![image](https://user-images.githubusercontent.com/113911141/191450670-793d1c93-1846-473f-a91a-c221c4fcd9c1.png)
Мій результат якщо я роблю випралення. Напевно воно все таке впливає, я не можу його прибрати. Я брала той клас з консолі, він не змінювався.
![image](https://user-images.githubusercontent.com/113911141/191450846-9e198604-201c-48a5-9a5f-cf23ca97caa6.png)

**Comment by jmas** [comment]
@anastasiiaShtepa ці класи генеруються автоматично на базі якогось алгоритма. Вони змінюються, тому їх треба замінити на якийсь інший клас, або селектор по тегу. Це не рекомендація. Це треба змінити, з такими класами я не зможу пропустити твій код.

**Comment by anastasiiaShtepa** [comment]
Done
